#!/bin/bash

# theme = "gruvbox material dark"
macos-option-as-alt = left
window-decoration = true
macos-titlebar-style = hidden
shell-integration-features = cursor

font-family = "CaskaydiaCove Nerd Font Mono"
font-size = 16

background-opacity = 0.9
background-blur-radius = 12

window-padding-x = 20
window-padding-y = 20
window-padding-balance = true

clipboard-read = allow
clipboard-write = allow
copy-on-select = true

background = #00111E
foreground = #CBE0F0

selection-background = #033259
selection-foreground = #CBE0F0

palette = 0=#214969
palette = 1=#E52E2E
palette = 2=#44FFB1
palette = 3=#FFE073
palette = 4=#0FC5ED
palette = 5=#a277ff
palette = 6=#24EAF7
palette = 7=#24EAF7

palette = 8=#214969
palette = 9=#E52E2E
palette = 10=#44FFB1
palette = 11=#FFE073
palette = 12=#A277FF
palette = 13=#a277ff
palette = 14=#24EAF7
palette = 15=#24EAF7
