#!/bin/bash

# theme = "gruvbox material dark"
macos-option-as-alt = left
window-decoration = true
macos-titlebar-style = hidden
shell-integration-features = cursor

font-family = "CaskaydiaCove Nerd Font Mono"
font-size = 17

adjust-cell-height = 20%

background-opacity = 0.9
background-blur-radius = 12

window-padding-x = 20
window-padding-y = 20
window-padding-balance = true

clipboard-read = allow
clipboard-write = allow
copy-on-select = true

background = #252423
foreground = #ebdbb2

selection-background = #45403d
selection-foreground = #ddc7a1

palette = 0=#282828
palette = 1=#ea6962
palette = 2=#a9b665
palette = 3=#d8a657
palette = 4=#7daea3
palette = 5=#d3869b
palette = 6=#89b482
palette = 7=#a89984

palette = 8=#928374
palette = 9=#fb4934
palette = 10=#b8bb26
palette = 11=#fabd2f
palette = 12=#83a598
palette = 13=#d3869b
palette = 14=#8ec07c
palette = 15=#ebdbb2
