#!/bin/bash

theme = "gruvbox material dark"
macos-option-as-alt = left
window-decoration = true
macos-titlebar-style = hidden
shell-integration-features = cursor

font-family = "CaskaydiaCove Nerd Font Mono"
font-size = 16

background-opacity = 0.9
background-blur-radius = 12

window-padding-x = 20
window-padding-y = 20
window-padding-balance = true

clipboard-read = allow
clipboard-write = allow
copy-on-select = true
