# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md#configuration
#file kanata_macos_cmd_allowed_arm64 renamed to kanata
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false
control_server_enable = false
control_server_port = 8100

[defaults]
kanata_executable = '~/.local/bin/kanata/
kanata_config = '~/.config/kanata/kanata.kbd'
tcp_port = 5829
autorestart_on_crash = false
autorun = true

[defaults.hooks]

[defaults.layer_icons]


[presets.'main cfg']
