#!/usr/bin/env zsh

###############################
#    ENVIRONMENT VARIABLES    #
###############################

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="${HOME}/.local/state"

# Dotfiles
export DOTFILES="$HOME/.dotfiles"

# ZSH

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Other Misc
export LOCATE_CONFIG="/etc/locate.users.rc" # Locate Command's Database
export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/bat/bat.conf"
export KANATA_TRAY_CONFIG_DIR="$XDG_CONFIG_HOME/kanata/kanata-tray.toml"

# Languages
[ -f "$HOME/.config/env/env.sh" ] && . "$HOME/.config/env/env.sh"
