#                _
#               | |
#        _______| |__  _ __ ___
#       |_  / __| '_ \| '__/ __|
#      _ / /\__ \ | | | | | (__
#     (_)___|___/_| |_|_|  \___|




source "${DOTFILES}/zsh/config/aliases.zsh"
source "${DOTFILES}/zsh/config/integrations.zsh"
source "${DOTFILES}/zsh/config/functions.zsh"
source "${DOTFILES}/zsh/config/paths.zsh"
source "${DOTFILES}/zsh/config/options.zsh"


